modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
[[mixins]]
config = "fwportals.common.mixins.json"
[[mixins]]
config = "fwportals.client.mixins.json"
[[mods]]
modId = "fwportals"
version = "${mod_version}"
displayName = "Forever World Portals"
description = "Server-side diamond-frame portal activation and recognition without teleportation yet."
displayTest = "IGNORE_ALL_VERSION"
[[dependencies.fwportals]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fwportals]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
